# Generated by Django 2.2 on 2021-04-14 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarLineApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_riders', to='CarLineApp.User'),
        ),
    ]
