# Generated by Django 2.2 on 2021-04-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarLineApp', '0002_auto_20210414_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='studentID',
            field=models.CharField(max_length=7),
        ),
    ]
