# Generated by Django 2.2 on 2021-04-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarLineApp', '0003_auto_20210416_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='carID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rider',
            name='grade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rider',
            name='studentID',
            field=models.IntegerField(),
        ),
    ]
